import type { Capability, CapabilityRuntimeMode } from "./types";

const ALL_AGENTS = [
  "agent-crawler",
  "agent-parser",
  "agent-synthesizer",
  "agent-qa",
  "agent-orchestrator",
];

export const runtimeModeLabels: Record<CapabilityRuntimeMode, string> = {
  "sdk-tool": "SDK 工具",
  "project-skill": "项目 Skill",
  "mcp-server": "MCP Server",
  "display-only": "展示",
};

export const capabilities: Capability[] = [
  {
    id: "mineru-parser",
    type: "mcp",
    runtimeMode: "sdk-tool",
    name: "MinerU Parser",
    subtitle: "文档智能解析工具",
    description:
      "面向 AI4S 数据生产的 PDF 解析能力，用于抽取论文版面、正文、公式、表格、图片和结构化 JSON。",
    category: "文档解析",
    tags: ["PDF", "OCR", "Layout", "Formula", "Table", "JSON", "AI4S"],
    featured: true,
    status: "enabled",
    recommendedAgentIds: ["agent-parser", "agent-synthesizer", "agent-orchestrator"],
    transport: "stdio",
    serverName: "mineru",
    command: "mineru-open-api",
    args: ["mcp"],
    tools: ["parse_pdf", "extract_layout", "extract_formula", "extract_table"],
    allowedTools: ["Bash", "Read", "Write", "Edit", "Glob", "Grep"],
  },
  {
    id: "filesystem-mcp",
    type: "mcp",
    runtimeMode: "mcp-server",
    name: "Filesystem MCP",
    subtitle: "受控文件系统访问",
    description:
      "基于官方 MCP filesystem server 的文件访问能力，用于受控读取和整理项目工作区文件。",
    category: "基础工具",
    tags: ["File", "Workspace", "MCP", "Read", "Write"],
    status: "enabled",
    sourceUrl: "https://github.com/modelcontextprotocol/servers",
    recommendedAgentIds: ALL_AGENTS,
    transport: "stdio",
    serverName: "filesystem",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-filesystem", "."],
    tools: ["read_file", "write_file", "list_directory"],
    allowedTools: ["mcp__filesystem__read_file", "mcp__filesystem__write_file"],
  },
  {
    id: "local-workspace",
    type: "mcp",
    runtimeMode: "sdk-tool",
    name: "Local Workspace",
    subtitle: "项目文件工作区",
    description:
      "管理项目目录中的论文、解析产物、训练数据和质检报告，作为所有 Agent 的基础文件能力。",
    category: "基础工具",
    tags: ["File", "Workspace", "Read", "Write"],
    status: "enabled",
    recommendedAgentIds: ALL_AGENTS,
    transport: "builtin",
    serverName: "workspace",
    tools: ["read_file", "write_file", "list_files"],
    allowedTools: ["Read", "Write", "Edit", "Glob", "Grep"],
  },
  {
    id: "python-sandbox",
    type: "mcp",
    runtimeMode: "sdk-tool",
    name: "Python Sandbox",
    subtitle: "数据处理沙箱",
    description:
      "用于解析产物清洗、JSON 转换、统计检查和批量数据后处理，适合数据合成与质检阶段。",
    category: "数据处理",
    tags: ["Python", "Transform", "Validate", "Batch"],
    status: "enabled",
    recommendedAgentIds: ["agent-synthesizer", "agent-qa"],
    transport: "builtin",
    serverName: "python-sandbox",
    tools: ["run_python", "validate_json", "convert_dataset"],
    allowedTools: ["Bash", "Read", "Write", "Edit"],
  },
  {
    id: "academic-search",
    type: "mcp",
    runtimeMode: "sdk-tool",
    name: "Academic Search",
    subtitle: "学术论文检索",
    description:
      "为论文爬取专家提供 arXiv、Semantic Scholar、OpenAlex 风格的检索入口，用于筛选 AI4S 相关论文。",
    category: "文献检索",
    tags: ["Search", "arXiv", "OpenAlex", "Paper"],
    status: "available",
    recommendedAgentIds: ["agent-crawler"],
    transport: "builtin",
    serverName: "academic-search",
    tools: ["search_papers", "fetch_metadata", "rank_relevance"],
    allowedTools: ["WebFetch", "Bash", "Read", "Write"],
  },
  {
    id: "web-crawler",
    type: "mcp",
    runtimeMode: "sdk-tool",
    name: "Web Crawler",
    subtitle: "网页抓取与正文抽取",
    description:
      "抓取 HTML 页面、提取正文、链接、标题和元数据，用于网页数据源进入 AI4S 数据流水线。",
    category: "网页处理",
    tags: ["HTML", "Crawler", "Metadata", "WebFetch"],
    status: "available",
    recommendedAgentIds: ["agent-crawler", "agent-parser"],
    transport: "builtin",
    serverName: "web-crawler",
    tools: ["fetch_html", "extract_links", "extract_main_text"],
    allowedTools: ["WebFetch", "Bash", "Read", "Write"],
  },
  {
    id: "html-extractor",
    type: "mcp",
    runtimeMode: "display-only",
    name: "HTML Extractor",
    subtitle: "HTML 到结构化内容",
    description:
      "将 HTML 页面解析成标题、正文、表格、链接和图片资源，适合网页报告与在线论文页面。",
    category: "网页处理",
    tags: ["HTML", "DOM", "Table", "Link"],
    status: "available",
    recommendedAgentIds: ["agent-parser"],
    transport: "http",
    serverName: "html-extractor",
    tools: ["parse_html", "extract_tables", "extract_links"],
    allowedTools: [],
  },
  {
    id: "docx-parser",
    type: "mcp",
    runtimeMode: "display-only",
    name: "DOCX Parser",
    subtitle: "Word 文档解析",
    description:
      "展示 Word/DOCX 文档解析能力，面向报告、说明书和结构化办公文档的数据抽取。",
    category: "文档解析",
    tags: ["DOCX", "Word", "Document", "Office"],
    status: "available",
    sourceUrl: "https://github.com/claude-office-skills/skills",
    recommendedAgentIds: ["agent-parser"],
    transport: "stdio",
    serverName: "office-doc",
    tools: ["read_docx", "extract_headings", "docx_to_markdown"],
    allowedTools: [],
  },
  {
    id: "spreadsheet-processor",
    type: "mcp",
    runtimeMode: "display-only",
    name: "Spreadsheet Processor",
    subtitle: "CSV / Excel 数据处理",
    description:
      "展示 CSV、XLSX 表格数据读取、清洗、列统计、字段映射和批量转换能力。",
    category: "表格处理",
    tags: ["CSV", "XLSX", "Excel", "Table"],
    status: "available",
    sourceUrl: "https://github.com/claude-office-skills/skills",
    recommendedAgentIds: ["agent-synthesizer", "agent-qa"],
    transport: "stdio",
    serverName: "spreadsheet",
    tools: ["read_sheet", "profile_columns", "xlsx_to_csv"],
    allowedTools: [],
  },
  {
    id: "json-validator",
    type: "mcp",
    runtimeMode: "sdk-tool",
    name: "JSON Schema Validator",
    subtitle: "JSON 结构校验",
    description:
      "对解析产物和训练数据进行 JSON 语法检查、Schema 校验、字段完整性检查和错误定位。",
    category: "质量评估",
    tags: ["JSON", "Schema", "Validate", "QA"],
    status: "enabled",
    recommendedAgentIds: ["agent-synthesizer", "agent-qa"],
    transport: "builtin",
    serverName: "json-validator",
    tools: ["validate_json", "schema_check", "repair_json"],
    allowedTools: ["Bash", "Read", "Write", "Edit"],
  },
  {
    id: "table-extractor",
    type: "mcp",
    runtimeMode: "display-only",
    name: "Table Extractor",
    subtitle: "跨格式表格抽取",
    description:
      "展示从 PDF、HTML、DOCX、CSV 中抽取表格并转换为统一 JSON/CSV 的能力。",
    category: "表格处理",
    tags: ["Table", "PDF", "HTML", "CSV"],
    status: "available",
    recommendedAgentIds: ["agent-parser", "agent-synthesizer"],
    transport: "stdio",
    serverName: "table-extractor",
    tools: ["extract_table", "normalize_table", "table_to_json"],
    allowedTools: [],
  },
  {
    id: "image-ocr",
    type: "mcp",
    runtimeMode: "display-only",
    name: "Image OCR",
    subtitle: "图像文字识别",
    description:
      "展示图片、扫描件、论文插图和截图中的文本识别能力，用于多模态文档解析。",
    category: "图像处理",
    tags: ["Image", "OCR", "Figure", "Multimodal"],
    status: "available",
    recommendedAgentIds: ["agent-parser"],
    transport: "stdio",
    serverName: "image-ocr",
    tools: ["ocr_image", "extract_caption", "detect_regions"],
    allowedTools: [],
  },
  {
    id: "deduplicator",
    type: "mcp",
    runtimeMode: "sdk-tool",
    name: "Data Deduplicator",
    subtitle: "样本去重",
    description:
      "基于文本相似度、字段哈希和规则检查，对生成样本进行去重和近重复聚类。",
    category: "质量评估",
    tags: ["Dedup", "Similarity", "Dataset", "QA"],
    status: "available",
    recommendedAgentIds: ["agent-qa"],
    transport: "builtin",
    serverName: "deduplicator",
    tools: ["hash_dataset", "find_duplicates", "cluster_similar"],
    allowedTools: ["Bash", "Read", "Write"],
  },
  {
    id: "dataset-profiler",
    type: "mcp",
    runtimeMode: "sdk-tool",
    name: "Dataset Profiler",
    subtitle: "数据集画像",
    description:
      "统计字段分布、缺失率、长度分布、标签覆盖和异常值，用于评估数据生产批次质量。",
    category: "质量评估",
    tags: ["Profile", "Stats", "Dataset", "Report"],
    status: "available",
    recommendedAgentIds: ["agent-qa", "agent-orchestrator"],
    transport: "builtin",
    serverName: "dataset-profiler",
    tools: ["profile_dataset", "summarize_fields", "detect_outliers"],
    allowedTools: ["Bash", "Read", "Write"],
  },
  {
    id: "mineru-pdf-skill",
    type: "skill",
    runtimeMode: "project-skill",
    name: "MinerU PDF 解析工作流",
    subtitle: "PDF 到结构化 JSON",
    description:
      "指导 Agent 优先使用 MinerU 解析科学论文，抽取标题、摘要、章节、公式、表格和图注，并整理成下游数据合成可用的 JSON。",
    category: "文档解析",
    tags: ["MinerU", "PDF", "Workflow", "JSON"],
    featured: true,
    status: "enabled",
    recommendedAgentIds: ["agent-parser"],
    dependsOn: ["mineru-parser"],
    skillPath: ".claude/skills/mineru-pdf/SKILL.md",
    triggerExamples: ["解析这批论文 PDF", "把 PDF 转成结构化 JSON", "抽取论文公式和表格"],
    promptSummary:
      "遇到论文 PDF 时，先执行 MinerU 解析，再按 AI4S 数据生产字段整理结构化结果。",
  },
  {
    id: "html-extraction-skill",
    type: "skill",
    runtimeMode: "project-skill",
    name: "HTML 页面抽取工作流",
    subtitle: "网页到结构化文本",
    description:
      "将 HTML 页面整理为标题、正文、表格、链接和元数据，并保留来源路径以便质检。",
    category: "网页处理",
    tags: ["HTML", "Parsing", "Metadata"],
    status: "available",
    recommendedAgentIds: ["agent-crawler", "agent-parser"],
    dependsOn: ["web-crawler"],
    skillPath: ".claude/skills/html-extraction/SKILL.md",
    triggerExamples: ["抽取网页正文", "把 HTML 转成结构化 JSON"],
    promptSummary:
      "处理 HTML 时优先保留正文结构、表格、链接和来源 URL。",
  },
  {
    id: "docx-parsing-skill",
    type: "skill",
    runtimeMode: "project-skill",
    name: "DOC/DOCX 文档解析工作流",
    subtitle: "办公文档结构化",
    description:
      "复用 Office 文档处理类 Skill 思路，将 Word 文档转换为结构化 Markdown/JSON。",
    category: "文档解析",
    tags: ["DOCX", "Office", "Markdown"],
    status: "available",
    sourceUrl: "https://github.com/claude-office-skills/skills",
    recommendedAgentIds: ["agent-parser"],
    dependsOn: ["docx-parser"],
    skillPath: ".claude/skills/docx-parsing/SKILL.md",
    triggerExamples: ["解析 Word 文档", "把 DOCX 转成 Markdown"],
    promptSummary:
      "处理 DOCX 时按标题层级、段落、表格和引用信息输出结构化内容。",
  },
  {
    id: "json-normalization-skill",
    type: "skill",
    runtimeMode: "project-skill",
    name: "JSON 清洗与规范化工作流",
    subtitle: "结构修复与字段规范",
    description:
      "对多源 JSON 数据进行字段映射、结构修复、Schema 对齐和异常记录。",
    category: "数据处理",
    tags: ["JSON", "Normalize", "Schema"],
    status: "available",
    recommendedAgentIds: ["agent-synthesizer", "agent-qa"],
    dependsOn: ["json-validator"],
    skillPath: ".claude/skills/json-normalization/SKILL.md",
    triggerExamples: ["清洗 JSON 数据", "修复字段结构", "对齐 schema"],
    promptSummary:
      "清洗 JSON 时保留原始字段映射，输出规范化结果和异常列表。",
  },
  {
    id: "spreadsheet-cleaning-skill",
    type: "skill",
    runtimeMode: "project-skill",
    name: "CSV/Excel 数据整理工作流",
    subtitle: "表格清洗与转换",
    description:
      "复用 Office 表格处理类 Skill 思路，完成 CSV/XLSX 读取、字段整理、缺失值检查和转换。",
    category: "表格处理",
    tags: ["CSV", "Excel", "XLSX", "Clean"],
    status: "available",
    sourceUrl: "https://github.com/claude-office-skills/skills",
    recommendedAgentIds: ["agent-synthesizer", "agent-qa"],
    dependsOn: ["spreadsheet-processor"],
    skillPath: ".claude/skills/spreadsheet-cleaning/SKILL.md",
    triggerExamples: ["整理 Excel 数据", "清洗 CSV", "统计表格字段"],
    promptSummary:
      "处理表格数据时检查列名、类型、缺失值和导出格式。",
  },
  {
    id: "multimodal-extraction-skill",
    type: "skill",
    runtimeMode: "project-skill",
    name: "图文多模态抽取工作流",
    subtitle: "图片、图注与正文关联",
    description:
      "将论文图片、图注、OCR 文本和上下文段落关联起来，形成多模态数据条目。",
    category: "图像处理",
    tags: ["Image", "OCR", "Caption", "Multimodal"],
    status: "available",
    recommendedAgentIds: ["agent-parser", "agent-synthesizer"],
    dependsOn: ["image-ocr"],
    skillPath: ".claude/skills/multimodal-extraction/SKILL.md",
    triggerExamples: ["抽取图片和图注", "生成图文样本"],
    promptSummary:
      "处理图片时同时保留图注、正文引用位置和 OCR 结果。",
  },
  {
    id: "sci-evo-generation",
    type: "skill",
    runtimeMode: "project-skill",
    name: "Sci-Evo 数据生成工作流",
    subtitle: "论文内容到训练样本",
    description:
      "基于论文结构化内容生成 Sci-Evo 风格训练数据，强调科学问题、方法、约束、实验和验证逻辑。",
    category: "数据合成",
    tags: ["Sci-Evo", "Dataset", "AI4S", "Synthesis"],
    status: "available",
    recommendedAgentIds: ["agent-synthesizer", "agent-orchestrator"],
    dependsOn: ["mineru-pdf-skill"],
    skillPath: ".claude/skills/sci-evo-generation/SKILL.md",
    triggerExamples: ["根据论文生成 Sci-Evo 数据", "合成 AI4S 训练样本"],
    promptSummary:
      "从解析后的论文内容中提炼科学任务，并生成结构完整、可质检的训练数据。",
  },
  {
    id: "data-quality-review",
    type: "skill",
    runtimeMode: "project-skill",
    name: "AI4S 数据质检工作流",
    subtitle: "科学性与完整性审核",
    description:
      "检查样本字段完整性、科学事实一致性、重复内容、幻觉风险和格式规范，并输出返修意见。",
    category: "质量评估",
    tags: ["QA", "Review", "Schema", "Risk"],
    status: "available",
    recommendedAgentIds: ["agent-qa"],
    skillPath: ".claude/skills/data-quality-review/SKILL.md",
    triggerExamples: ["质检这些训练数据", "检查 JSON 字段完整性", "找出幻觉风险"],
    promptSummary:
      "按结构、科学性、可验证性和数据格式四个维度检查 AI4S 样本。",
  },
  {
    id: "dedup-review-skill",
    type: "skill",
    runtimeMode: "project-skill",
    name: "数据去重与覆盖分析工作流",
    subtitle: "重复样本与覆盖检查",
    description:
      "对生成数据做重复、近重复、字段覆盖和主题覆盖分析，输出保留、合并和删除建议。",
    category: "质量评估",
    tags: ["Dedup", "Coverage", "QA"],
    status: "available",
    recommendedAgentIds: ["agent-qa"],
    dependsOn: ["deduplicator", "dataset-profiler"],
    skillPath: ".claude/skills/dedup-review/SKILL.md",
    triggerExamples: ["检查重复样本", "分析数据覆盖率"],
    promptSummary:
      "先识别重复和近重复，再评估字段与主题覆盖，最后给出处理建议。",
  },
  {
    id: "literature-screening-skill",
    type: "skill",
    runtimeMode: "project-skill",
    name: "文献检索筛选工作流",
    subtitle: "论文检索与筛选",
    description:
      "从检索结果中按领域、年份、方法、数据质量和相关性筛选适合进入数据生产的论文。",
    category: "文献检索",
    tags: ["Paper", "Search", "Ranking"],
    status: "available",
    recommendedAgentIds: ["agent-crawler", "agent-orchestrator"],
    dependsOn: ["academic-search"],
    skillPath: ".claude/skills/literature-screening/SKILL.md",
    triggerExamples: ["筛选 AI4S 论文", "按主题检索论文"],
    promptSummary:
      "筛选论文时记录纳入、排除和待复核理由，并输出可追踪列表。",
  },
  {
    id: "pipeline-orchestration",
    type: "skill",
    runtimeMode: "project-skill",
    name: "多 Agent 流水线编排工作流",
    subtitle: "爬取、解析、合成、质检",
    description:
      "将论文爬取、MinerU 解析、数据合成和质检返修串成可追踪任务链路，适合流程编排专家使用。",
    category: "流程编排",
    tags: ["Agent", "Pipeline", "Orchestration"],
    status: "available",
    sourceUrl: "https://github.com/OneWave-AI/claude-skills",
    recommendedAgentIds: ["agent-orchestrator"],
    skillPath: ".claude/skills/pipeline-orchestration/SKILL.md",
    triggerExamples: ["启动一批论文数据生产流水线", "为这些 PDF 分配 Agent 任务"],
    promptSummary:
      "把数据生产拆成多个 Agent 任务，并根据状态推进、返修或终止。",
  },
];

export const featuredCapabilityId = "mineru-parser";
