import type { Capability } from "./types";

export const capabilities: Capability[] = [
  {
    id: "mineru-parser",
    type: "mcp",
    name: "MinerU Parser",
    subtitle: "文档智能解析工具",
    description:
      "面向 AI4S 数据生产的 PDF 解析能力，用于抽取论文版面、正文、公式、表格、图片和结构化 JSON。",
    category: "文档解析",
    tags: ["PDF", "OCR", "Layout", "Formula", "Table", "JSON", "AI4S"],
    featured: true,
    status: "enabled",
    recommendedAgentIds: ["agent-parser", "agent-synthesizer", "agent-orchestrator"],
    transport: "stdio",
    serverName: "mineru",
    command: "mineru-open-api",
    args: ["mcp"],
    tools: ["parse_pdf", "extract_layout", "extract_formula", "extract_table"],
    allowedTools: ["mcp__mineru__parse_pdf", "mcp__mineru__extract_layout"],
  },
  {
    id: "academic-search",
    type: "mcp",
    name: "Academic Search",
    subtitle: "学术论文检索",
    description:
      "为论文爬取专家提供 arXiv、Semantic Scholar、OpenAlex 风格的检索入口，用于筛选 AI4S 相关论文。",
    category: "文献检索",
    tags: ["Search", "arXiv", "OpenAlex", "Paper"],
    status: "available",
    recommendedAgentIds: ["agent-crawler"],
    transport: "http",
    serverName: "academic-search",
    tools: ["search_papers", "fetch_metadata", "rank_relevance"],
    allowedTools: ["mcp__academic_search__search_papers"],
  },
  {
    id: "local-workspace",
    type: "mcp",
    name: "Local Workspace",
    subtitle: "项目文件工作区",
    description:
      "管理项目目录中的论文、解析产物、训练数据和质检报告，作为所有 Agent 的基础文件能力。",
    category: "基础工具",
    tags: ["File", "Workspace", "Read", "Write"],
    status: "enabled",
    recommendedAgentIds: [
      "agent-crawler",
      "agent-parser",
      "agent-synthesizer",
      "agent-qa",
      "agent-orchestrator",
    ],
    transport: "builtin",
    serverName: "workspace",
    tools: ["read_file", "write_file", "list_files"],
    allowedTools: ["Read", "Write", "Edit", "Glob", "Grep"],
  },
  {
    id: "python-sandbox",
    type: "mcp",
    name: "Python Sandbox",
    subtitle: "数据处理沙箱",
    description:
      "用于解析产物清洗、JSON 转换、统计检查和批量数据后处理，适合数据合成与质检阶段。",
    category: "数据处理",
    tags: ["Python", "Transform", "Validate", "Batch"],
    status: "available",
    recommendedAgentIds: ["agent-synthesizer", "agent-qa"],
    transport: "stdio",
    serverName: "python-sandbox",
    command: "python",
    args: ["-m", "sandbox_mcp"],
    tools: ["run_python", "validate_json", "convert_dataset"],
    allowedTools: ["mcp__python_sandbox__run_python"],
  },
  {
    id: "mineru-pdf-skill",
    type: "skill",
    name: "MinerU PDF 解析工作流",
    subtitle: "PDF 到结构化 JSON",
    description:
      "指导 Agent 优先使用 MinerU 解析科学论文，抽取标题、摘要、章节、公式、表格和图注，并整理成下游数据合成可用的 JSON。",
    category: "文档解析",
    tags: ["MinerU", "PDF", "Workflow", "JSON"],
    featured: true,
    status: "enabled",
    recommendedAgentIds: ["agent-parser"],
    dependsOn: ["mineru-parser"],
    skillPath: ".claude/skills/mineru-pdf/SKILL.md",
    triggerExamples: ["解析这批论文 PDF", "把 PDF 转成结构化 JSON", "抽取论文公式和表格"],
    promptSummary:
      "遇到论文 PDF 时，先执行 MinerU 解析，再按 AI4S 数据生产字段整理结构化结果。",
  },
  {
    id: "sci-evo-generation",
    type: "skill",
    name: "Sci-Evo 数据生成工作流",
    subtitle: "论文内容到训练样本",
    description:
      "基于论文结构化内容生成 Sci-Evo 风格训练数据，强调科学问题、方法、约束、实验和验证逻辑。",
    category: "数据合成",
    tags: ["Sci-Evo", "Dataset", "AI4S", "Synthesis"],
    status: "available",
    recommendedAgentIds: ["agent-synthesizer", "agent-orchestrator"],
    dependsOn: ["mineru-pdf-skill"],
    skillPath: ".claude/skills/sci-evo-generation/SKILL.md",
    triggerExamples: ["根据论文生成 Sci-Evo 数据", "合成 AI4S 训练样本"],
    promptSummary:
      "从解析后的论文内容中提炼科学任务，并生成结构完整、可质检的训练数据。",
  },
  {
    id: "data-quality-review",
    type: "skill",
    name: "AI4S 数据质检工作流",
    subtitle: "科学性与完整性审核",
    description:
      "检查样本字段完整性、科学事实一致性、重复内容、幻觉风险和格式规范，并输出返修意见。",
    category: "质量评估",
    tags: ["QA", "Review", "Schema", "Risk"],
    status: "available",
    recommendedAgentIds: ["agent-qa"],
    skillPath: ".claude/skills/data-quality-review/SKILL.md",
    triggerExamples: ["质检这些训练数据", "检查 JSON 字段完整性", "找出幻觉风险"],
    promptSummary:
      "按结构、科学性、可验证性和数据格式四个维度检查 AI4S 样本。",
  },
  {
    id: "pipeline-orchestration",
    type: "skill",
    name: "多 Agent 流水线编排工作流",
    subtitle: "爬取、解析、合成、质检",
    description:
      "将论文爬取、MinerU 解析、数据合成和质检返修串成可追踪任务链路，适合流程编排专家使用。",
    category: "流程编排",
    tags: ["Agent", "Pipeline", "Orchestration"],
    status: "available",
    recommendedAgentIds: ["agent-orchestrator"],
    skillPath: ".claude/skills/pipeline-orchestration/SKILL.md",
    triggerExamples: ["启动一批论文数据生产流水线", "为这些 PDF 分配 Agent 任务"],
    promptSummary:
      "把数据生产拆成多个 Agent 任务，并根据状态推进、返修或终止。",
  },
];

export const featuredCapabilityId = "mineru-parser";

