import type { Project, Agent, Task, Event, Toast } from "./types";

const now = Date.now();

export const projects: Project[] = [
  {
    id: "6cfaf851-29c9-42c4-bd6e-9af14979ef89",
    name: "AI4S-Data-Swarm",
    path: "E:/2026Mineru比赛",
    description: "AI4S 数据合成流水线项目",
    createdAt: now,
    updatedAt: now,
  },
];

export const agents: Agent[] = [
  {
    id: "agent-crawler",
    name: "论文爬取专家",
    avatar: "🔍",
    role: "学术论文检索与下载",
    prompt: "你是一个学术论文爬取专家。",
    isEnabled: true,
    status: "idle",
    projectId: "6cfaf851-29c9-42c4-bd6e-9af14979ef89",
    maxTurns: 150,
    maxBudgetUsd: 3,
    allowedTools: ["Bash", "Read", "Write", "Edit", "Grep", "Glob", "WebFetch"],
    model: "",
    apiKey: "",
    apiBaseUrl: "",
    taskCount: 0,
    stats: {
      totalTasksCompleted: 0,
      totalTasksCancelled: 0,
      totalCostUsd: 0,
      avgDurationMs: 0,
    },
    lastEventAt: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-parser",
    name: "PDF 解析专家",
    avatar: "📚",
    role: "使用 MinerU 解析论文PDF为结构化JSON",
    prompt: "你是一个学术论文 PDF 解析专家。",
    isEnabled: true,
    status: "idle",
    projectId: "6cfaf851-29c9-42c4-bd6e-9af14979ef89",
    maxTurns: 150,
    maxBudgetUsd: 5,
    allowedTools: ["Bash", "Read", "Write", "Edit", "Grep", "Glob"],
    model: "",
    apiKey: "",
    apiBaseUrl: "",
    taskCount: 0,
    stats: {
      totalTasksCompleted: 0,
      totalTasksCancelled: 0,
      totalCostUsd: 0,
      avgDurationMs: 0,
    },
    lastEventAt: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-synthesizer",
    name: "数据合成专家",
    avatar: "🎯",
    role: "基于论文内容生成高质量训练数据",
    prompt: "你是一个 AI4S 训练数据合成专家。",
    isEnabled: true,
    status: "idle",
    projectId: "6cfaf851-29c9-42c4-bd6e-9af14979ef89",
    maxTurns: 200,
    maxBudgetUsd: 5,
    allowedTools: ["Bash", "Read", "Write", "Edit", "Grep", "Glob"],
    model: "",
    apiKey: "",
    apiBaseUrl: "",
    taskCount: 0,
    stats: {
      totalTasksCompleted: 0,
      totalTasksCancelled: 0,
      totalCostUsd: 0,
      avgDurationMs: 0,
    },
    lastEventAt: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-qa",
    name: "质检专家",
    avatar: "🔬",
    role: "对合成训练数据进行质量审核",
    prompt: "你是一个训练数据质检专家。",
    isEnabled: true,
    status: "idle",
    projectId: "6cfaf851-29c9-42c4-bd6e-9af14979ef89",
    maxTurns: 150,
    maxBudgetUsd: 3,
    allowedTools: ["Bash", "Read", "Write", "Edit", "Grep", "Glob"],
    model: "",
    apiKey: "",
    apiBaseUrl: "",
    taskCount: 0,
    stats: {
      totalTasksCompleted: 0,
      totalTasksCancelled: 0,
      totalCostUsd: 0,
      avgDurationMs: 0,
    },
    lastEventAt: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "agent-orchestrator",
    name: "流程编排专家",
    avatar: "🛠️",
    role: "编排 AI4S 数据合成流水线",
    prompt: "你是 AI4S 数据合成流水线的编排专家。",
    isEnabled: true,
    status: "idle",
    projectId: "6cfaf851-29c9-42c4-bd6e-9af14979ef89",
    maxTurns: 200,
    maxBudgetUsd: 5,
    allowedTools: ["Bash", "Read", "Write", "Edit", "Grep", "Glob"],
    model: "",
    apiKey: "",
    apiBaseUrl: "",
    taskCount: 0,
    stats: {
      totalTasksCompleted: 0,
      totalTasksCancelled: 0,
      totalCostUsd: 0,
      avgDurationMs: 0,
    },
    lastEventAt: 0,
    createdAt: now,
    updatedAt: now,
  },
];

export const tasks: Task[] = [];

export const events: Event[] = [];

export const toasts: Toast[] = [];
